### ISSUE TITLE
Don't you use a version manager?

### ISSUE THREAD

**Issue by kkeri** [zkat/ama#10]
On [toolsday](http://www.toolsday.io/episodes/npx.html) you said "I don't use a version manager myself". Would you explain it please? Partly because I'm not very well at understanding live english, but anyway it is surprising enough to be asked.

**Comment by zkat** [comment]
@kkeri By version manager, I mean specifically something that manages node versions. Tools like [nvm](https://npm.im/nvm), [nave](https://npm.im/nave), [n](https://npm.im/n), etc.

Before [npx](https://npm.im/npx) I was using nave as my preferred switcher, but it would break sometimes. I refuse to use nvm because of its wrapper shims, and n looked pretty cool but I didn't have much of a chance to really try it. It's worth noting that I have sort of special requirements here, since I work with a globally-linked npm, and a lot of version managers mess with which npm you have globally available -- at least they will often shadow it.

These days, I just run the latest node as my main one, and rely on CI to make sure everything works across supported versions. If I want to run something with a different node version, though, I'll do, for example, `npx -p node@7 npm t` to run my test suite with node7.

Hope that answers your question!

**Comment by kkeri** [comment]
@zkat My question revealed that I'm not too familiar with the node ecosystem yet, so it was useful to ask. Thank you!
