### ISSUE TITLE
What's a way to start to contributing to npm or getting started to work on package managers?

### ISSUE THREAD

**Issue by lucas-aragno** [zkat/ama#11]

**Comment by zkat** [comment]
Probably the best way to get started with npm contribution right now is to look for issues to tackle in [pacote](https://npm.im/pacote), [make-fetch-happen](https://npm.im/make-fetch-happen), and [cacache](https://npm.im/cacache). I'm also looking for someone who would be willing/able to port [Molinillo]() to JS in a way that's compatible with pacote, since we're hoping to use that algorithm for a related package manager for frontend users.

As we extract more chunks of npm into smaller external libraries, I'm hoping we'll see a lot more useful contribution to the project. 👍  There's some projects already taking advantage of this, such as [cipm](https://github.com/zkat/cipm).

You might also want to join [package.community](https://package.community), which is where we coordinate a lot of our work and talk about the future. It's not just npm folks there, either -- it's a general community for package manager devs.
