### ISSUE TITLE
What was the "interview gauntlet" at Microsoft like?

### ISSUE THREAD

**Issue by cuibonobo** [zkat/ama#15]
First of all, if you prefer a different contact format or just don't have time to answer, feel free to close this issue. I initially thought of sending you an email or Twitter DM, but since this repo was still open I figured I would give it a shot.

In a recent [comment on your Dev.to AMA](https://dev.to/zkat/comment/f2ak), you mentioned that at first you cancelled the on-site interview because the idea of going through an "interview gauntlet" stressed you out. Can you describe what that interview process was like?

I have been making software at an animation studio for about 5 years now and I'm really proud of the tools that I've built, but the lack of resources and support are pushing me to consider applying to a software company. My degree is in Electrical Engineering, not CompSci, so the gaps in my knowledge are giving me anxiety.

I've been following you on Twitter for a few years now and I decided to reach out directly because we're both Boricua women, so I figured your perspective would align more with my own.

Thanks and solidarity.

**Comment by zkat** [comment]
The "interview gauntlet" at Microsoft was pretty boring as far as these processes go:

1. Initial contact with recruiter
2. "warm body" phone screen
3. fly out to Redmond and get interviewed by several people over the course of a day, with technical tests during each conversation (all whiteboarding stuff). The whiteboarding was all around algorithmic thinking and problem solving, not exactly stuff like reversing a linked list, but not too far from that. idk what else I can say about it, I see it as pretty standard stuff.
4. Wait. A while.

As far as CompSci vs other majors go, maybe it'll help you to know that all I have is a BA in Film? It's definitely slowed down my career progression (I've been at this for 12 years), and there's definitely people in much higher places at MSFT who have done this for as long as I have, straight out of college.

My best recommendation is to take on the weight of learning the hard CompSci stuff yourself, working through algorithms book like Cormen, and go out of your day-to-day work to really master your particular domain. I know this is all kinda hand-wavy but that's how these things are, I think. I did spend a lot of time just self-teaching CS and coding in my spare time, but I also hate giving people advice that they should focus a lot of their spare time on extracurriculars because that's also the road to burnout and losing work/life balance (something I'm working very hard to regain now).

Interviewing is definitely a skill all on its own, and it doesn't have as much overlap over day-to-day work as it should. My best advice aside from preparing your algorithmic skills in general is "always ask questions and talk through your thought process out loud. Communicate, communicate, communicate". Sometimes that's more important than being able to solve the problem on the whiteboard.

I hope this answers your question!

**Comment by zkat** [comment]
(and yes, this repo is still up so folks can ask stuff like this! You can also DM me on twitter any time!)
