### ISSUE TITLE
What is the coolest macro you've ever written?

### ISSUE THREAD

**Issue by MysteryMachine** [zkat/ama#2]
Whenever a LISP programmer gets to write a non-trivial macro, it is a damn good day for them. What is the coolest thing you've used a macro to do?

**Comment by zkat** [comment]
The thing about macro writing is that if the macro itself is big and complicated, you're probably doing it wrong. Often, good macros get broken down into syntax sugar for more interesting functionality.

That said, maybe one of these:
- I reimplemented a lot of CLOS, [but with prototypes instead of classes](https://github.com/zkat/sheeple), so I ended up rewriting a lot of core macros: [`defmessage`](https://github.com/zkat/sheeple/blob/master/src/messages.lisp#L228-L236) (which is like `defgeneric`), and [`defproto`](https://github.com/zkat/sheeple/blob/master/src/objects.lisp#L477-L490) (which is kinda like `defclass`) -- you can see how small the macros themselves are, and how they call a bunch of different functions to generate what they need to.
- I also wrote a DSL that was largely based around functions for defining bullet hell levels in a little game a wrote way back when, that looks like this: https://github.com/zkat/yashmup/blob/master/levels/test-level.lisp
- my function code _has_ gotten pretty gnarly for the sake of providing good interfaces, though, with this one being probably the most notorious the I like linking: [`make-actor-function`](https://github.com/zkat/memento-mori/blob/old-mori/src/actor.lisp#L210-L250) from my failed attempt at writing Erlang's OTP into Common Lisp :)
- Usually, when I was writing CL, it was @adlai who would come up with the gnarliest/fanciest macros, such as when he rewrote [`select`](https://github.com/zkat/chanl/blob/master/src/select.lisp#L14-L73) from my original version into this fascinating monstrosity ;)
