### ISSUE TITLE
When did you know you were a "programmer"?

### ISSUE THREAD

**Issue by varjmes** [zkat/ama#3]
n/A

**Comment by zkat** [comment]
I don't remember really struggling with "programmer". I definitely struggled for a while about whether to call myself a "hacker" because I was neck-deep in that culture. I still think "hacker" gets across a certain attitude and attachment to programming and greybeardy things like unixy stuff, but is a terrible measure of "good programmer", much less "good person", so I tend to not worry about it. I usually just say it to emphasize that I'm one of those people that likes hacking nonsense code for fun in my spare time and that I've absorbed a lot of hacker culture's little cultural artifacts from my time in IRC.

But back to your question -- I don't see "programmer" as a term that has a very high bar at all without qualifiers. If you can sit down and use whatever tool you happen to be used to and give a computer an algorithm to work with, then you're a programmer. Period.

If what you want to become is a "capable software engineer", most of the skillset is orthogonal to raw hacking skill: I see software engineering as being almost entirely about people, organizational structure, project and product management, process, and then some baseline familiarity with whatever tools you work with on your day to day so they're not getting in the way of all the shit you actually gotta do. Being able to wrap your head around architecture, learning good practices, being able to deal with the _very rare_ occurrence of a complex algorithm being needed at your job, etc, are all things that come naturally over time -- specially if it happens to be a hobby or external interest, but just showing up at work will get you to improve enough.

**Comment by varjmes** [comment]
Thank you! :)
