### ISSUE TITLE
What is the best general programming book you've ever read?

### ISSUE THREAD

**Issue by MysteryMachine** [zkat/ama#5]
📖

**Comment by zkat** [comment]
There's a few I wanna recommend! It depends on what you mean by "general programming": I consider all the items on the list below to be fantastic, generally-applicable books about programming, but they all teach different things. Of course, they're largely lisp-based, but I don't think it's a coincidence that a lot of really good books for stuff like this (symbolic computation, programming language theory, compilers) came out of the Lisp world, cause they're all such core concepts to so many Lisp programmers, and because of Lisp's use in academia for a long time.
- My favorite "introduction to programming" book, by far, is [Gentle Introduction to Symbolic Computation](https://www.amazon.com/Common-LISP-Introduction-Computation-Engineering/dp/0486498204) -- it's really showing its age, and it's nominally a Lisp book, but I would recommend it to literally anyone who wants to get started, because the book does a fabulous job of teaching you how to _think_ of computation. It spends a significant amount of time in the beginning chapters without showing you any code whatsoever -- just visual, box-based metaphors for function calls. I'm convinced this helped me form the way I think about code in a really unique way, very early on.
- For growing and mastering the design of protocol-based/Object-Oriented programs. [Art of the Metaobject Protocol](https://www.amazon.com/Art-Metaobject-Protocol-Gregor-Kiczales/dp/0262610744/) is the best text I've ever seen that walks people through the _process_ of starting from something rigid, and redesigning parts of it for extensibility as needed, and making sure those changes have minimal impact.
- I read [Cormen's Introduction to Algorithms](https://www.amazon.com/Introduction-Algorithms-3rd-MIT-Press/dp/0262033844) very early on, with my first mentor giving me chapters to read and answering questions. I think it's particularly important for programmers who learned to code outside academia to actually take the time to work through books like these. Computer Science isn't just woo-woo stuff or solving absurd problems, it's about the very nature of solving problems, and this book does a great job of teaching about how algorithms work, how to design them, how to understand their characteristics, and then also teaches you a few fundamental algorithms and datastructures that are fundamental to being able to effectively communicate about what you're doing and contextualizing your day-to-day work.
- [Lisp in Small Pieces](https://www.amazon.com/Lisp-Small-Pieces-Christian-Queinnec/dp/0521545668) was a really fantastic, step-by-step introduction to interpreters and compilers, and is where I draw the vast majority of my understanding of compilers, particularly JavaScript compilers (which are very similar to Lisp ones). This book also has an intro to denotational semantics, but I couldn't wrap my head around that at the time. It's also very hands-on so you can actually _run_ what you write.
- [Design Concepts in Programming Languages](https://www.amazon.com/Design-Concepts-Programming-Languages-Press/dp/0262201755/) pretty fundamentally shaped how I see programming languages, paradigms, features, and really inspired me about possibilities.

**Comment by adlai** [comment]
@zkat I must say... I am disappoint. It's alright to send people into the rainforest for titles unavailable otherwise (at least, not without _real_ effort), but why not link to fulltext if it's available? None of these were beyond the first page of search results, so don't sue me, just file a DMCA if you're pissed.

[Gentle Introduction to Symbolic Computation](https://www.cs.cmu.edu/~dst/LispBook/book.pdf)

[Art of the Metaobject Protocol](http://buhoz.net/public/books/lenguajes/lisp/Art_of_the_Metaobject_Protocol_1993.djvu)

[Introduction to Algorithms](http://bayanbox.ir/view/4177858657730907268/introduction-to-algorithms-3rd-edition.pdf)

[Lisp in Small Pieces](http://buhoz.net/public/books/lenguajes/lisp/Lisp.In.Small.Pieces.djvu)

[Design Concepts in Programming Languages](http://web.eecs.umich.edu/~bchandra/courses/papers/Turbak_6.821/book.pdf)

BRB, downloading all of http://buhoz.net/public/books/lenguajes/lisp/

**Comment by zkat** [comment]
@adlai thanks bruh

 [![I speak for the trees](http://media.avclub.com/images/articles/article/69/69864/lorax3_jpg_627x325_crop_upscale_q85.jpg)]()

**Comment by abdulhannanali** [comment]
Thank you @zkat You are very awesome. Thanks a lot for sharing these links. I am going to get started  with the first book. Although, I know a bit of JavaScript, it's going to be interesting to learn how LISP works, but more importantly I am reading it to learn thinking in computation. <3 <3 <3
