### ISSUE TITLE
What is your favorite package?

### ISSUE THREAD

**Issue by legodude17** [zkat/ama#9]
What is your favorite package on `npm`? 😄

**Comment by zkat** [comment]
That's a tricky one! Of course I'm biased, so [npm](https://npm.im/npm) is the one I like most. After that, I love [`fuck-you`](https://www.npmjs.com/package/fuck-you) as a system-wide utility for killing processes. I'm also a big fan of [`mississippi`](https://npm.im/mississippi) because it managed to wrangle Node streams into something relatively palatable. Or at least useful.
